# Generated by Django 2.2.7 on 2019-11-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TweetLabelerRequestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.CharField(default='', max_length=120)),
                ('password', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
